### ISSUE TITLE
Fix pretty printing @-expressions

### ISSUE THREAD

**Issue by tkers** [liphe/delisp#69]
The pretty printer rewrites an at-expression like `@doc{Hello World}` into `(doc "Hello World")`, but the original notation should be maintained.

https://github.com/ams-hackers/delisp/blob/c0b03065e7f1e2192024eb640f304acca82a905f/packages/delisp-core/__tests__/printer.ts#L62-L64

**Comment by davazp** [comment]
As we focus on the structured editor, this should not be a problem anymore. Closing it.
